[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "christmas_orchestrator"
version = "0.1.0"
dependencies = [
    "naptha-sdk==0.1.3",
    "browser-use-sdk==0.1.0",
    "websockets>=11.0,<15.0"
]
